<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 15:02:54.
 */
class Object_FilterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Object_Filter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Object_Filter('value1','key1');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	

    /**
     * @covers Object_Filter::filter
     */
    public function testFilter()
    {
        $this->object_default = new Object_Filter('value1');

		$this->assertTrue($this->object_default->filter('value1'));
		$this->assertFalse($this->object_default->filter('value2'));

		$a_default = array('group' => 'value1');
		$this->assertTrue($this->object_default->filter($a_default));
		
		$a_default = array('group' => 'value2');
		$this->assertFalse($this->object_default->filter($a_default));

		$a = array('key1' => 'value1');
		$this->assertTrue($this->object->filter($a));
		
		$a = array('key1' => 'value2');
		$this->assertFalse($this->object->filter($a));
		
		$a = array('key2' => 'value1');
		$this->assertFalse($this->object->filter($a));

    }

	/**
     * @expectedException Core_InvalidArgumentValueException
     */
    public function testCreateWithNull()
    {
		$this->assertFalse(new Object_Filter('value1',null));
	}		
	
}
