<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 14:54:04.
 */
class Object_ModuleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Object::AttrList
     */
    public function testAttrList()
    {
		$this->assertInstanceOf('Object_AttrList',$this->object->AttrList());
	}

    /**
     * @covers Object::Listener
     */
    public function testListener()
    {
		$this->assertInstanceOf('Object_Listener',$this->object->Listener());
    }

    /**
     * @covers Object::Factory
     */
    public function testFactory()
    {
		$this->assertInstanceOf('Object_Factory',$this->object->Factory());
    }

    /**
     * @covers Object::Aggregator
     */
    public function testAggregator()
    {
		$this->assertInstanceOf('Object_Aggregator',$this->object->Aggregator());
    }

    /**
     * @covers Object::Wrapper
     */
    public function testWrapper()
    {
		$this->assertInstanceOf('Object_Wrapper',$this->object->Wrapper(new ArrayObject));
    }

    /**
     * @covers Object::Filter
     */
    public function testFilter()
    {
		$this->assertInstanceOf('Object_Filter',$this->object->Filter('aaaa'));
    }
}
