<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 09:45:46.
 */
class Validation_Commons_ConfirmationTestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Validation_Commons_ConfirmationTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Validation_Commons_ConfirmationTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Validation_Commons_ConfirmationTest::test
     * @todo   Implement testTest().
     */
    public function testTest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
