<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 09:40:41.
 */
class Validation_Commons_EmailTestTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Validation_Commons_EmailTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Validation_Commons_EmailTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
