<?php
  //TODO: разобраться с путями для layout
  $this->allow_filtering(false);
  $this->no_duplicates_in('js');
  // $this->use_onpage_to_file('js');
  // $this->use_onpage_to_file('css');
  $this->meta->http_content_type = "text/html; charset=utf-8";
	$title = CMS::lang(trim(CMS::vars()->get('admin.title')));
	$this->meta->title = $title;
	$this->use_script(CMS_Admin::$jquery, array('type' => 'lib', 'weight' => -20));
	if (!isset($logo_width)) $logo_width = 140;
	if (!isset($logo_height)) $logo_height = 80;
	$this->
		use_styles('/tao/styles/normalize.css')->
		use_styles('/tao/styles/admin/layout.css')->
		use_styles('/tao/styles/admin/menu.css')->
		use_styles('/tao/styles/admin/controls.css')->
		use_styles('/tao/styles/jquery/modalbox.css')->
		use_scripts('/tao/scripts/jquery/popup/modalbox.js')->
		use_scripts('/tao/scripts/help.js')->
		use_scripts('/tao/scripts/jquery/cookie.js');
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <?= $this['head'] ?>
</head>

<body>
  <?php Events::call('cms.admin.layout.body.begin'); ?>

  <?php if (isset(CMS::$globals['is_embedded_admin'])) { $title = isset(CMS::$globals['embedded_admin_title'])?CMS::$globals['embedded_admin_title']:'Администрирование'; ?>
  <div id="topmenu">
    <ul class="level1">
      <li class="first"><a href="/"><span>Просмотр сайта</span></a></li>
      <li class="last current"><a href=""><span><?= $title ?></span></a></li>
    </ul>
  </div>
  <?php } else { ?>
  <div id="topbar"><a href="<?= CMS::admin_path() ?>"><?= $title ?></a></div>
  <div id="topmenu"><?= CMS::navigation()->draw('admin') ?></div>
  <?php } ?>
  <div id="content"><?= $this['content']; ?></div>

  <?php if (!isset(CMS::$globals['is_embedded_admin'])) { ?>
    <?= CMS_Admin::subsites_menu() ?>
    <?= CMS_Admin::admin_menu() ?>
    <a id="toplogo" href="<?= CMS::admin_path() ?>" style="background-image: url(<?= CMS_Admin::logo() ?>) ">&nbsp;</a>
  <?php } ?>

  <?php Events::call('cms.admin.layout.body.end'); ?>
</body>
</html>

