<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 12:20:09.
 */
class Validation_ModuleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Validation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Validation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Validation::initialize
     */
    public function testInitialize()
    {
    }

    /**
     * @covers Validation::use_tests
     * @todo   Implement testUse_tests().
     */
    public function testUse_tests()
    {
		//$this->assertInstanceOf('Validation',$this->object->use_tests(array(),''));
    }

    /**
     * @covers Validation::use_test
     * @todo   Implement testUse_test().
     */
    public function testUse_test()
    {
		//$this->assertInstanceOf('Validation',$this->object->use_test('class','class_name'));
    }

    /**
     * @covers Validation::Validator
     */
    public function testValidator()
    {
		$this->assertInstanceOf('Validation_Validator',$this->object->Validator());
    }

    /**
     * @covers Validation::make_test
     * Протестирована в при тесте Validation_Validator::__call
     */
    public function testMake_test()
    {
    }
}
