<?php
	$this->use_script(CMS_Admin::$jquery, array('type' => 'lib', 'weight' => -20));
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
  <?= $this->stylesheet_link_tag('/files/_assets/styles/admin-layout.css') ?>
  <?= $this->stylesheet_link_tag('/files/_assets/styles/admin-menu.css') ?>
  <?= $this->stylesheet_link_tag('/files/_assets/styles/admin-controls.css') ?>
  <?= $this['head'] ?>
  <?= $this->javascript_include_tag('/files/_assets/scripts/bgiframe.js') ?>
  <?= $this->javascript_include_tag('/files/_assets/scripts/trhover.js') ?>
</head>

<body>
  <div id="content"><?= $this['content']; ?></div>
</body>
</html>

