<?php
	$this->use_script(CMS_Admin::$jquery, array('type' => 'lib', 'weight' => -20));
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
  <?= $this->stylesheet_link_tag('/tao/styles/admin/layout.css') ?>
  <?= $this->stylesheet_link_tag('/tao/styles/admin/menu.css') ?>
  <?= $this->stylesheet_link_tag('/tao/styles/admin/controls.css') ?>
  <?= $this['head'] ?>
</head>

<body>
  <div id="content"><?= $this['content']; ?></div>
</body>
</html>

