<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
  <title><?= htmlspecialchars($title) ?></title>

  <style>
	  body { background-color: white; }
	  body, body * { font-family: arial, helvetica, sans-serif }
	  h1 { font-size: 24px; }
	  h2 { font-size: 18px; font-weight: normal; }
	  div.block { margin: 10px; background-color: #eee; border: 1px dotted #888; padding: 10px 10px 10px 30px; font-size: 12px; position: relative; }
	  span.num {position: absolute; top: 10px; left: 5px; width: 20px; text-align: right;}
	  div.file {font-size:10px;color: #888;}
  </style>

</head>

<body>
	<?php
		$file = trim($e->getFile());
		$line = $e->getLine();
		if ($file!='') print "<div class='efile'>$file ($line)</div>";

	?>
	<h1><?= $e->getMessage() ?></h2>
	<h2>Backtrace:</h2>

	<?php	$btc = 0;
		$bt = $e->getTrace();
		foreach($bt as $t) { $btc++; ?>
			<div class="block">
				<span class="num"><?= $btc ?>.</span>
				<div class="header">
					<div class="call"><?= isset($t['class'])?$t['class']:'' ?><?= isset($t['type'])?$t['type']:'' ?><?= $t['function'] ?>(<?= self::render_array($t['args']) ?>)</div>
					<?php if (isset($t['file'])&&isset($t['line'])) { ?>
					<div class="file"><?= $t['file'] ?> (<?= $t['line'] ?>)</div>
					<?php } ?>
				</div>
			</div>
	<?php	}


	?>



</body>
</html>

