<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 14:53:45.
 */
class DB_ORM_MapperSetTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_ORM_MapperSet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_ORM_MapperSet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_ORM_MapperSet::submappers
     * @todo   Implement testSubmappers().
     */
    public function testSubmappers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_MapperSet::with_submappers
     * @todo   Implement testWith_submappers().
     */
    public function testWith_submappers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_MapperSet::submapper
     * @todo   Implement testSubmapper().
     */
    public function testSubmapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_MapperSet::with_submapper
     * @todo   Implement testWith_submapper().
     */
    public function testWith_submapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_MapperSet::__can_map
     * @todo   Implement test__can_map().
     */
    public function test__can_map()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_MapperSet::__map
     * @todo   Implement test__map().
     */
    public function test__map()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
