<?php
/**
 * Класс для тестирования класса DB_ORM_SQLMapper.
 * 
 * Нужно проверить работу метода __call на вызов методов типа 
 * map_{имя_свойства}, pmap_{имя_свойства}, cmap_{имя_свойства}.
 */
class DB_ORM_SQLMapper_For_Test extends DB_ORM_SQLMapper
{
	
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-15 at 14:51:32.
 */
class DB_ORM_SQLMapperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_ORM_SQLMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_ORM_SQLMapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_ORM_SQLMapper::__name
     * @todo   Implement test__name().
     */
    public function test__name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::mode
     * @todo   Implement testMode().
     */
    public function testMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::distinct
     * @todo   Implement testDistinct().
     */
    public function testDistinct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::option
     * @todo   Implement testOption().
     */
    public function testOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::immutable
     * @todo   Implement testImmutable().
     */
    public function testImmutable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::preload
     * @todo   Implement testPreload().
     */
    public function testPreload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::associate_table_for
     * @todo   Implement testAssociate_table_for().
     */
    public function testAssociate_table_for()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::table_from
     * @todo   Implement testTable_from().
     */
    public function testTable_from()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::id_from
     * @todo   Implement testId_from().
     */
    public function testId_from()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::as_string
     * @todo   Implement testAs_string().
     */
    public function testAs_string()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::map_associated_with
     * @todo   Implement testMap_associated_with().
     */
    public function testMap_associated_with()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::map_dissociated_with
     * @todo   Implement testMap_dissociated_with().
     */
    public function testMap_dissociated_with()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::associate_with
     * @todo   Implement testAssociate_with().
     */
    public function testAssociate_with()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::dissociate_with
     * @todo   Implement testDissociate_with().
     */
    public function testDissociate_with()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::make_entity
     * @todo   Implement testMake_entity().
     */
    public function testMake_entity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::not_in
     * @todo   Implement testNot_in().
     */
    public function testNot_in()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::in
     * @todo   Implement testIn().
     */
    public function testIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::as_array
     * @todo   Implement testAs_array().
     */
    public function testAs_array()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::query
     * @todo   Implement testQuery().
     */
    public function testQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::select
     * @todo   Implement testSelect().
     */
    public function testSelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::select_first
     * @todo   Implement testSelect_first().
     */
    public function testSelect_first()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::select_for
     * @todo   Implement testSelect_for().
     */
    public function testSelect_for()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::select_first_for
     * @todo   Implement testSelect_first_for().
     */
    public function testSelect_first_for()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::stat
     * @todo   Implement testStat().
     */
    public function testStat()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::stat_all
     * @todo   Implement testStat_all().
     */
    public function testStat_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::filter
     * @todo   Implement testFilter().
     */
    public function testFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::find
     * @todo   Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::lookup
     * @todo   Implement testLookup().
     */
    public function testLookup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::search
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::update_all
     * @todo   Implement testUpdate_all().
     */
    public function testUpdate_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::insert
     * @todo   Implement testInsert().
     */
    public function testInsert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::delete_all
     * @todo   Implement testDelete_all().
     */
    public function testDelete_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::count
     * @todo   Implement testCount().
     */
    public function testCount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::spawn_for
     * @todo   Implement testSpawn_for().
     */
    public function testSpawn_for()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::paginate_with
     * @todo   Implement testPaginate_with().
     */
    public function testPaginate_with()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::getIterator
     * @todo   Implement testGetIterator().
     */
    public function testGetIterator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::access
     * @todo   Implement testAccess().
     */
    public function testAccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::sql
     * @todo   Implement testSql().
     */
    public function testSql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__call
     * @todo   Implement test__call().
     */
    public function test__call()
    {
		var_dump($this->object->any('any'));die;
    }

    /**
     * @covers DB_ORM_SQLMapper::offsetGet
     * @todo   Implement testOffsetGet().
     */
    public function testOffsetGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::offsetSet
     * @todo   Implement testOffsetSet().
     */
    public function testOffsetSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::offsetExists
     * @todo   Implement testOffsetExists().
     */
    public function testOffsetExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::offsetUnset
     * @todo   Implement testOffsetUnset().
     */
    public function testOffsetUnset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__set
     * @todo   Implement test__set().
     */
    public function test__set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__isset
     * @todo   Implement test__isset().
     */
    public function test__isset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_ORM_SQLMapper::__unset
     * @todo   Implement test__unset().
     */
    public function test__unset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
