<?php

//require_once 'PHPUnit/Autoload.php';

//

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 12:37:25.
 */
class Core_ModuleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Core
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Core;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Core::initialize
     * @todo   Implement testInitialize().
     */
    public function testInitialize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::start_time
     * @todo   Implement testStart_time().
     */
    public function testStart_time()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::is_flush_modules_cache
     * @todo   Implement testIs_flush_modules_cache().
     */
    public function testIs_flush_modules_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::options
     * @todo   Implement testOptions().
     */
    public function testOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::option
     * @todo   Implement testOption().
     */
    public function testOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::register_spl_autoload
     * @todo   Implement testRegister_spl_autoload().
     */
    public function testRegister_spl_autoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::spl_autoload
     * @todo   Implement testSpl_autoload().
     */
    public function testSpl_autoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::cached_modules
     * @todo   Implement testCached_modules().
     */
    public function testCached_modules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::flush_modules_cache
     * @todo   Implement testFlush_modules_cache().
     */
    public function testFlush_modules_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::find_all_modules
     * @todo   Implement testFind_all_modules().
     */
    public function testFind_all_modules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::loader
     * @todo   Implement testLoader().
     */
    public function testLoader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::configure
     * @todo   Implement testConfigure().
     */
    public function testConfigure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::is_loaded
     * @todo   Implement testIs_loaded().
     */
    public function testIs_loaded()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::equals
     * @todo   Implement testEquals().
     */
    public function testEquals()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::object
     * @todo   Implement testObject().
     */
    public function testObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::hash
     * @todo   Implement testHash().
     */
    public function testHash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::cached_invoke
     * @todo   Implement testCached_invoke().
     */
    public function testCached_invoke()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::clear_invoke_cache
     * @todo   Implement testClear_invoke_cache().
     */
    public function testClear_invoke_cache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::is_cli
     * @todo   Implement testIs_cli().
     */
    public function testIs_cli()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::with
     * @todo   Implement testWith().
     */
    public function testWith()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::with_clone
     * @todo   Implement testWith_clone().
     */
    public function testWith_clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::with_index
     * @todo   Implement testWith_index().
     */
    public function testWith_index()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::with_attr
     * @todo   Implement testWith_attr().
     */
    public function testWith_attr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::if_null
     * @todo   Implement testIf_null().
     */
    public function testIf_null()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::if_not
     * @todo   Implement testIf_not().
     */
    public function testIf_not()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::if_false
     * @todo   Implement testIf_false().
     */
    public function testIf_false()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::if_not_set
     * @todo   Implement testIf_not_set().
     */
    public function testIf_not_set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::make
     * @todo   Implement testMake().
     */
    public function testMake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::amake
     * @todo   Implement testAmake().
     */
    public function testAmake()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::replace_class
     * @todo   Implement testReplace_class().
     */
    public function testReplace_class()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::current_replace_class_for
     * @todo   Implement testCurrent_replace_class_for().
     */
    public function testCurrent_replace_class_for()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::replace_class_map
     * @todo   Implement testReplace_class_map().
     */
    public function testReplace_class_map()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::replace_class_maps
     * @todo   Implement testReplace_class_maps().
     */
    public function testReplace_class_maps()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::enable_autoload
     * @todo   Implement testEnable_autoload().
     */
    public function testEnable_autoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::disable_autoload
     * @todo   Implement testDisable_autoload().
     */
    public function testDisable_autoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::autoload
     * @todo   Implement testAutoload().
     */
    public function testAutoload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Core::normalize_args
     * @todo   Implement testNormalize_args().
     */
    public function testNormalize_args()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
