<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-22 at 14:32:40.
 */
class Time_ModuleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Time
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Time;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Time::DateTime
     */
    public function testDateTime()
    {
		$this->assertEquals(Time::DateTime(), new Time_DateTime());

		$t = new Time_DateTime();
		$this->assertEquals(Time::DateTime($t->getTimestamp()), new Time_DateTime($t));
		
		$this->assertEquals(Time::DateTime($t), new Time_DateTime($t));
    }

    /**
     * @covers Time::now
     */
    public function testNow()
    {
		$this->assertEquals(Time::now(), new Time_DateTime);
    }

    /**
     * @covers Time::seconds_between
     */
    public function testSeconds_between()
    {
		$seconds = 10;
		$from = new Time_DateTime();
		$to = new Time_DateTime();
		$to->sub_seconds($seconds);
		
		$this->assertEquals($seconds, Time::seconds_between($from, $to));
    }
}
