<div class="field">
	<?= $ccont ?>
	<div class="right">
		<?php 
			if ($type_object->validator_tagparms($name,$data,$tagparms)) {
				$validation_js = 'scripts/validation.js';
				$vjs = $validation_js;
				Events::call("cms.fields.{$form->name}.validation.js",$validation_js);
				if ($validation_js) {
					if ($vjs==$validation_js) $validation_js = CMS::stdfile_url($validation_js);
					$this->use_scripts($validation_js);
				}
			}
			$_name = $name; print $this->partial($template, array('_name' => $_name))
		?><?= ($rcaption?" $rcaption":'') ?>

		<?php if (!empty($selected_formats)):?>
		<div class="input-formats input-formats-<?php print $_name ?>">
			<?= $this->forms->select_tag($type_object->input_formats_name($name, $data), $selected_formats, $data['default input format']); ?>
		</div>
		<?php endif; ?>

		<?php if (isset($data['comment'])) { ?>
		<div class="comment"><?= $data['comment'] ?></div>
		<?php } ?>
	</div>
</div>
