<?php
$this->use_styles(CMS::stdfile_url('styles/stockroom.css'));
$this->use_scripts(CMS::stdfile_url('scripts/admin/table-edit.js'));
$title = 'Обновление компонента '.$item->title;
?>
<?php include($controller->template('prepare')); ?>
<?php include($controller->template('header')); ?>
<?php if ($error) { ?>
<p class="error"><?= $error ?></p>
<?php } else { ?>
<p>В настоящий момент установлена версия <?= $item->installed() ?> компонента. Вы действительно желаете обновить этот компонент до версии <?= $item['version'] ?>?</p>
<form method="post" action="<?= $controller->action_url('update',$item) ?>"><input type="submit" class="submit-button" value="Начать обновление"></form>
<?php } ?>
