<div class="brdr">
	<form method="post" action="<?= $_change ?>">
	<table width="100%" cellspacing="1" cellpadding="0" border="0">
	<tr><td class="use-tab-key"><textarea wrap="off" id="valuesrc_textarea" name="valuesrc" style="width:98%;height:400px;"><?= htmlspecialchars($item->valuesrc) ?></textarea></td></tr>
	<tr><td><input class="submit-button" type="submit" value="<?= CMS::lang()->_vars->submit_edit ?>"></td></tr></table>
	</form>

</div>
