<div class="brdr">
	<form method="post" action="<?= $_change ?>">
	<table width="100%" cellspacing="1" cellpadding="0" border="0"><tr>
		<td width="100%"><input type="text" name="value" style="width:98%" value="<?= htmlspecialchars($item->value) ?>"></td>
		<td><input  class="submit-button" type="submit" value="<?= htmlspecialchars(CMS::lang()->_vars->submit_edit) ?>"></td>
	</tr></table>
	</form>

</div>