<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 16:28:35.
 */
class EventsObserverTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Events_Observer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Events_Observer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Events_Observer::get_dispatcher
     * @todo   Implement testGet_dispatcher().
     */
    public function testGet_dispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Observer::enable_dispatch
     * @todo   Implement testEnable_dispatch().
     */
    public function testEnable_dispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Observer::disable_dispatch
     * @todo   Implement testDisable_dispatch().
     */
    public function testDisable_dispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Observer::dispatch
     * @todo   Implement testDispatch().
     */
    public function testDispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Observer::dispatch_res
     * @todo   Implement testDispatch_res().
     */
    public function testDispatch_res()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
