<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 16:27:57.
 */
class EventsDispatcherTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Events_Dispatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Events_Dispatcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Events_Dispatcher::current_event
     * @todo   Implement testCurrent_event().
     */
    public function testCurrent_event()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::add_listeners
     * @todo   Implement testAdd_listeners().
     */
    public function testAdd_listeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::add_listener
     * @todo   Implement testAdd_listener().
     */
    public function testAdd_listener()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::add_once
     * @todo   Implement testAdd_once().
     */
    public function testAdd_once()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::add_with_context
     * @todo   Implement testAdd_with_context().
     */
    public function testAdd_with_context()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::add_subscriber
     * @todo   Implement testAdd_subscriber().
     */
    public function testAdd_subscriber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::has_listeners
     * @todo   Implement testHas_listeners().
     */
    public function testHas_listeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Dispatcher::dispatch
     * @todo   Implement testDispatch().
     */
    public function testDispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
