<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 16:21:10.
 */
class EventsTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Events
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Events;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Events::Dispatcher
     * @todo   Implement testDispatcher().
     */
    public function testDispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::Event
     * @todo   Implement testEvent().
     */
    public function testEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::add_listener
     * @todo   Implement testAdd_listener().
     */
    public function testAdd_listener()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::add_once
     * @todo   Implement testAdd_once().
     */
    public function testAdd_once()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::add_with_context
     * @todo   Implement testAdd_with_context().
     */
    public function testAdd_with_context()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::add_subscriber
     * @todo   Implement testAdd_subscriber().
     */
    public function testAdd_subscriber()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::add_listeners
     * @todo   Implement testAdd_listeners().
     */
    public function testAdd_listeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::call
     * @todo   Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::dispatch
     * @todo   Implement testDispatch().
     */
    public function testDispatch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events::current_event
     * @todo   Implement testCurrent_event().
     */
    public function testCurrent_event()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
