<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-22 at 16:29:11.
 */
class EventsSubscriberTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Events_Subscriber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Events_Subscriber;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Events_Subscriber::autodiscover
     * @todo   Implement testAutodiscover().
     */
    public function testAutodiscover()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Events_Subscriber::get_events
     * @todo   Implement testGet_events().
     */
    public function testGet_events()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
