<?php
	$this->use_styles(CMS::stdfile_url('styles/jquery/tabs.css'));
	$this->use_script(CMS::stdfile_url('scripts/jquery/tabs.js'), array('weight' => -10));
	$key = md5(WS::env()->request->path);

	$tabs_parms = array('fxAutoHeight' => true);
	Events::call("cms.table.tabs_parms",$tabs_parms);
	Events::call("{$mnemocode}.tabs_parms",$tabs_parms);
?>

<ul class="tabs-nav">
<?php foreach($form_tabs as $tab => $data) { ?>
	<li><a href="#formtab-<?= $tab.$key ?>"><span><?= $data['caption'] ?></span></a></li>
<?php } ?>
</ul>

<?php foreach($form_tabs as $tab => $data) { ?>
	<div id="formtab-<?= $tab.$key ?>" class="tabs-container">
		<?php include($controller->template('form-table')); ?>
	</div>
<?php } ?>

<?php $this->begin('js'); ?>
$(function(){
	$('#admin-table-form-tabs-<?= $key ?>').tabs_light(<?= json_encode($tabs_parms) ?>);
});
<?php $this->end('js'); ?>
