<div class="admin-table-right-buttons">
	<?php Events::call("$mnemocode.rightbuttons"); ?>
	<?php if (isset($list_url)&&isset($list_button_caption)&&$list_url!=''&&$list_button_caption!='') { ?>
	<a href="<?= $list_url ?>" class="with-icon button-list"><em><?= CMS::lang($list_button_caption) ?></em></a>
	<?php } ?>
	<?php if (isset($can_add)&&$can_add) { ?>
	<a href="<?= $add_url ?>" class="with-icon button-add"><em><?= CMS::lang($add_button_caption) ?></em></a>
	<?php } ?>
</div>
<h1><?= $title ?></h1>