<?php
	$template_table_before_row = $controller->template('list-table-before-row');
	$template_table_row = $controller->template('list-table-row');
	$template_table_after_row = $controller->template('list-table-after-row');

	$list_fields_templates_tds = array();
	$list_fields_templates_values = array();
	if (!empty($list_fields)) {
		foreach($list_fields as $field => $data) {
			$list_fields_templates_tds[$field] = $controller->redefined_template("list-table-row-td-{$field}");
			$list_fields_templates_values[$field] = $controller->redefined_template("list-table-row-field-{$field}");
		}
	}
	
	foreach($rows as $row) {
		include($template_table_row);
	}

?>
