<?php 
$this->no_layout();

$config = WS::env()->config;
if (isset($config->cms)&&isset($config->cms->password_encoder)) {
	if (!$config->cms->password_encoder) {
		$controller->not_found();
	}
}


?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>Password encoder</title>
	</head>
	
	<body>
		<form method="post" action="/cms-password-encoder/">
			<input type="password" name="password" value="<?= $_POST['password'] ?>" style="border: 1px solid #888;width:200px;">
			<input type="submit" value=">>" style="border: 1px solid #ccc; background-color: #eee">
		</form>
		
		<?php if (isset($_POST['password'])&&trim($_POST['password'])!='') { sleep(5); ?>
		<div style="margin: 20px 0;border: 1px solid #800; padding: 10px; color: #800; width: 400px;"><?= Digest::password(trim($_POST['password'])) ?></div>
		<?php } ?>
		
	</body>
</html>