<?php
	$this->use_scripts(CMS::stdfile_url('scripts/ajaxupload.js'));
	$c = CMS::$current_controller;
	$lang = CMS::lang()->_common;
	//$files = $type_object->filelist($form[$name], $da);
	$this->use_styles(CMS::stdfile_url('styles/fields/attaches.css'));

	$vname = preg_replace('{[^a-z0-9_]+}','',$name);
?>

<div class="addattache" id="add-attache-<?= $name ?>-<?= $url_class?>" data-url="<?= $c->field_action_url($name,'upload',$item,array('code'=>$type_object->temp_code())) ?>"
	data-url-reload="<?= $c->field_action_url($name,'reload',$item,array('code'=>$type_object->temp_code())) ?>">
	<p class="add-attache-caption"><?= $type_object->get_add_file_text($name, $data) ?></p>
	<div class="attaches-load-indicator" id="attaches-load-indicator-<?= $name ?>">&nbsp;</div>
</div>
<?php $this->begin('js1'); ?>
<!--
	$(function() {

		new AjaxUpload("add-attache-<?= $name ?>", {
			action: '<?= $c->field_action_url($name,'upload',$item,array('code'=>$type_object->temp_code())) ?>',
			name: 'attachement',
			autoSubmit: true,
			responseType: false,
			onSubmit: function(file, extension){
				$("#attaches-load-indicator-<?= $name ?>").show();
			},
			onComplete: function(file, resp){
				$("#attaches-load-indicator-<?= $name ?>").hide();
				if (resp!='success') {
					alert(resp);
				}

				else {
					listReload();
				}
			}
		});
		
		$("#attaches-list-<?= $name ?>")[0].__reload = function() {
			var $list = $(this);
			$list.load('<?= $c->field_action_url($name,'reload',$item,array('code'=>$type_object->temp_code())) ?>',{},
			 function() {bindsDeleteAttachment(); $list.trigger('reload', [$list, 'delete']);});
			bindsDeleteAttachment();
		}
		
		bindsDeleteAttachment();

		function listReload() {
			var $list = $("#attaches-list-<?= $name ?>");
			$list.load('<?= $c->field_action_url($name,'reload',$item,array('code'=>$type_object->temp_code())) ?>',{},
			 function() {bindsDeleteAttachment(); $list.trigger('reload', [$list, 'upload']);});
			bindsDeleteAttachment();
		}

		function bindsDeleteAttachment() {
			$(".delete-attachment").unbind('click').click(function() {
				var $d_link = $(this);
				if (confirm("<?= CMS::lang()->_common->ta_dfconfirm ?>")) {
					var href = $(this).attr('href');
					$.get(href, function() {$d_link.parents('div.attaches-list')[0].__reload()});
					return false;
				}
				return false;
			});
		}

	});
//-->
<?php $this->end('js1'); ?>
