<?php
	$this->use_scripts(CMS::stdfile_url('scripts/ajaxupload.js'));
	$c = CMS::$current_controller;
	$lang = CMS::lang()->_common;
	//$files = $type_object->filelist($form[$name], $da);
	$this->use_styles(CMS::stdfile_url('styles/fields/attaches.css'));

	$vname = preg_replace('{[^a-z0-9_]+}','',$name);
?>

<div class="addattache" id="add-attache-<?= $name ?>-<?= $url_class?>" data-url="<?= $c->field_action_url($name,'upload',$item,array('code'=>$type_object->temp_code())) ?>"
	data-url-reload="<?= $c->field_action_url($name,'reload',$item,array('code'=>$type_object->temp_code())) ?>">
	<p class="add-attache-caption"><?= $type_object->get_add_file_text($name, $data) ?></p>
	<div class="attaches-load-indicator" id="attaches-load-indicator-<?= $name ?>">&nbsp;</div>
</div>