<style>

.with_border { border: 1px solid #ccc; }

ul.ufiles { padding: 10px; }
ul.unfiles { padding: 10px; color: red; }

div.repository_dir {
	border: 1px dotted #88f;
	background-color: #fff;
	padding: 5px 0 5px 30px;
	margin: 0 0 3px 0;
	background-image: url(/image/admin/icon_folder.gif);
	background-repeat: no-repeat;
	background-position: 5px 2px;
}

	div.repository_dir a {
		font-size: 14px;
		color: #262;
		text-decoration: none;
	}


div.repository_component {
	border: 1px dotted #88f;
	background-color: #fff;
	padding: 5px 5px 5px 30px;
	margin: 0 0 3px 0;
}

	div.repository_component a {
		font-size: 14px;
		color: #226;
		display: block;
	}

	div.repository_component div.version {
		color: #fff;
		font-size: 12px;
		font-weight: bold;
		padding: 0 10px 0 10px;
		float: right;
	}

	div.repository_component div.update {
		background-color: #822;
	}	

	div.repository_component div.noupdate {
		background-color: #363;
	}	

div.documentation { padding: 3px;}

	div.documentation pre { font-size: 12px; font-family: monospace;}
	
	div.documentation ul {
		margin: 0 0 20px 30px;
	}

	div.documentation div.php, div.documentation div.sql {
		border: 1px dotted #ccc;
		background-color: #eee;
		padding: 5px 0 5px 10px;
		margin: 0 0 10px 0;
	}

		div.documentation div.php p { padding:0; margin: 0; }
		div.documentation div.php span.comment { color: #888; }
		div.documentation div.php span.str { color: #282; }
		div.documentation div.php span.var { color: #822; }

</style>