<form method="post" name="form_schema" action="<?= $c->schema_url() ?>" target="_blank" onSubmit="return checkFormSchema(this)">
<input type="hidden" name="table" value="">
<table class="form">	
<tr>
	<th nowrap>Имя компонента:</th>
	<td><input type="text" name="component" style="width:300px;" value="<?= htmlspecialchars($component_name) ?>"></td>
</tr>	
<tr>
	<th nowrap>&nbsp;</th>
	<td><input type="submit" value="Создать схему"></td>
</tr>	
</table>
</form>

<script type="text/javascript">
<!--
function checkFormSchema(f) {
	if (f.table.value=='') {
		alert('Не указана таблица БД!');
		return false;
	}
	if (f.component.value=='') {
		alert('Не указано имя компонента!');
		f.component.focus();
		return false;
	}
}
//-->
</script>