<?php
print CMS::stdstyle('tabs.css');
print CMS::stdstyle('factory.css');
print CMS::stdscript('tabs.js');
?>
<h1>Создание объектов</h1>

<table border="0" width="100%" cellspacing="0" cellpadding="0"><tr>
  <td valign="top">
    <div id="leftnavigation" class="round-corners">
      <h4>Таблицы в БД:</h4>
      <ul id="tablesnavigation">
        <?php foreach($tables as $table) { ?>
          <li><a href="#<?= $table ?>"><?= $table ?></a></li>
        <?php } ?>
      </ul>
    </div>
  </td>
  <td valign="top">&nbsp;</td>
  <td valign="top" width="100%">

    <div id="formtabs">
      <ul class="tabs-nav">
        <li><a href="#formtab-component"><span>Компонент</span></a></li>
        <li><a href="#formtab-entity"><span>Бизнес-логика</span></a></li>
        <li><a href="#formtab-schema"><span>Схема</span></a></li>
        <li><a href="#formtab-admin"><span>Администратор</span></a></li>
      </ul>



      <div id="formtab-component" class="tabs-container">
        <div id="formtabc-component">
          <h2>Создание компонента с нуля</h2>
          <p>Данный режим позволяет на основании таблицы БД создать новый компонент, включающий в себя: 
             маппер, объект бизнес-логики, контроллер табличного администрирования и пустой контроллер.</p>
             <div class="formtab-form round-corners"><?php include('form-component.phtml'); ?></div>
        </div>    
      </div>	
		
      <div id="formtab-entity" class="tabs-container tabs-hide">
        <div id="formtabc-entity">
          <h2>Создание объекта бизнес-логики</h2>
          <p>Данный режим позволяет на основании таблицы БД создать объект бизнес-логики.</p>
          <div class="formtab-form round-corners"><?php include('form-entity.phtml'); ?></div>
        </div>    
      </div>

      <div id="formtab-schema" class="tabs-container tabs-hide">
        <div id="formtabc-schema">
          <h2>Создание схемы (DB.Schema) таблицы</h2>
          <p>Данный режим позволяет на основании таблицы БД создать схему и сохранить её в файл.</p>
          <div class="formtab-form round-corners"><?php include('form-schema.phtml'); ?></div>
        </div>    
      </div>	
		
      <div id="formtab-admin" class="tabs-container tabs-hide">
        <div id="formtabc-admin">
          <h2>Создание контроллера табличного администрирования</h2>
          <p>Данный режим позволяет на основании таблицы БД создать контроллер табличного администрирования.</p>
          <div class="formtab-form round-corners"><?php include('form-admin.phtml'); ?></div>
        </div>    
      </div>	
	
	</div>
	
	
  </td>

</tr></table>

<script type="text/javascript">
<!--

$(function(){
	
	var currentTable = false; 
	var currentAT = false; 
	
	$('#formtabs').tabs();
	
	var h1 = $('#tablesnavigation').height(); 
	var h2 = $('#formtabc-component').height(); 
	var h3 = $('#formtabc-entity').height(); 
	var h4 = $('#formtabc-admin').height();
	
	var hmax = h1;
	hmax = h2>hmax?h2:hmax;
	hmax = h3>hmax?h3:hmax;
	hmax = h4>hmax?h4:hmax;

	$('#tablesnavigation').height(hmax+10);
	$('#formtabc-component').height(hmax); 
	$('#formtabc-entity').height(hmax); 
	$('#formtabc-admin').height(hmax);
	$('#formtabc-schema').height(hmax);
	 
	
	$('#tablesnavigation li a ').click(function(){
		if (currentAT) currentAT.removeClass('selected');
		currentAT = $(this).addClass('selected');
		var table = currentAT.attr('href').replace('#','');
		selectTable(table);
		return false;
	});
});


function selectTable(table) {
	document.form_component.table.value = table;
	document.form_entity.table.value = table;
  document.form_schema.table.value = table;
	document.form_admin.table.value = table;
	var t1 = table.slice(0,1).toUpperCase();
	var ts = table.slice(1);
	var tt = table;
	document.form_component.component.value = t1+ts;
	document.form_entity.module.value = 'Component.'+t1+ts+'.DB';
	document.form_schema.component.value = t1+ts;
	document.form_admin.emodule.value = 'Component.'+t1+ts+'.DB';
	document.form_admin.orm.value = tt;
	document.form_admin.module.value = 'Component.'+t1+ts+'.AdminController';
}
//-->
</script>
