<?php if (!CMS_Factory::$use_style) include('css.inc'); ?>
<div class="documentation">
  <h1><?= $class->title ?></h1>
  <?= $class->ok_description() ?>
  
  <?php if (sizeof($class->install_errors)>0) { ?>
  <h2>Обнаружены ошибки:</h2>
  <div class="errors"><ul>
	<?php foreach($class->install_errors as $q) { ?>
	<li><?= $q ?>;</li>
	<?php } ?>
  </ul></div>
  <?php } ?>
  
  <?php if ($class->component_dir&&file_exists("../app/components/$class->component_dir/.info")) { ?>
    <p>
    	В каталоге <b>app/components/<?= $class->component_dir ?></b> сохранен файл <b>.info</b>, содержащий информацию об установленной версии компонента, и его файлах.
    	Не удаляйте этот файл и не редактируйте его если хотите, чтобы у вас осталась возможность обновлять версии компонента.
    </p>
  <?php } ?>
  
  
  <?php if (sizeof($class->queries_log)>0) { ?>
  <h2>Была произведена модификация БД:</h2>
  <div class="sql"><pre>
	<?php foreach($class->queries_log as $q) echo htmlspecialchars("\n$q;\n"); ?>
  </pre></div>
  <?php } ?>
  
  <?php if (Core_Types::is_iterable($class->dumps_log)&&sizeof($class->dumps_log)>0) { ?>
  <h2>Были загружены дампы:</h2>
  <ul class="dumps">
	<?php foreach($class->dumps_log as $q) {
		$sq = $q;
		if ($m = Core_Regexps::match_with_results('{/([^/]+)$}',$sq)) $sq = $m[1];
		echo "<li><a href='".$c->admin_download_url($q)."'>$sq</a></li>\n";
	} ?>
  </ul>
  <?php } ?>
  
  <?php if ($class->string_exists_in($class->files_log)) { ?>
  <h2>Были скопированы файлы:</h2>
  <div class="with_border">
  <ul id="copiedfiles" class="pagetree"><?php ftree($class,$class->files_log); ?></ul>
  </div>
  <?php } ?>
  
  <?php function ftree($class,$ls) { 
  	foreach($ls as $f => $data) if ($class->string_exists_in($data)) { 
  		echo '<li>';
  		if (is_string($data)) echo "<span class='file'>$f</span>";
  		else {
  			echo "<span class='folder'>$f</span>";
  			echo '<ul>';
  			ftree($class,$data);
  			echo '</ul>';
  		}	
  		echo '</li>';
  	}
  } ?>
  
</div>

<?php
$this->use_scripts(CMS_Admin::$jquery);
print CMS::stdstyle('tree.css');
print CMS::stdscript('tree.js');

?>
<script type="text/javascript">
<!--
$(function() {        
        $("#copiedfiles").treeview({
                collapsed: false,
                unique: false
        });
});        

//-->
</script>
