<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-21 at 15:42:29.
 */
class DB_Adapter_PDO_Connection_ForTest extends DB_Adapter_PDO_Connection
{
	public function cast_parameter($value)
	{
	}
}

class DB_Adapter_PDO_ConnectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_Adapter_PDO_Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_Adapter_PDO_Connection_ForTest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_Adapter_PDO_Connection::set_attribute
     * @todo   Implement testSet_attribute().
     */
    public function testSet_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::get_attribute
     * @todo   Implement testGet_attribute().
     */
    public function testGet_attribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::transaction
     * @todo   Implement testTransaction().
     */
    public function testTransaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::commit
     * @todo   Implement testCommit().
     */
    public function testCommit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::rollback
     * @todo   Implement testRollback().
     */
    public function testRollback()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::last_insert_id
     * @todo   Implement testLast_insert_id().
     */
    public function testLast_insert_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::quote
     * @todo   Implement testQuote().
     */
    public function testQuote()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_PDO_Connection::after_connect
     * @todo   Implement testAfter_connect().
     */
    public function testAfter_connect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
