<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-21 at 15:45:19.
 */
class DB_Adapter_MySQL_ConnectionTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_Adapter_MySQL_Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_Adapter_MySQL_Connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::cast_parameter
     * @todo   Implement testCast_parameter().
     */
    public function testCast_parameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::is_castable_parameter
     * @todo   Implement testIs_castable_parameter().
     */
    public function testIs_castable_parameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::after_connect
     * @todo   Implement testAfter_connect().
     */
    public function testAfter_connect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::explain
     * @todo   Implement testExplain().
     */
    public function testExplain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::get_schema
     * @todo   Implement testGet_schema().
     */
    public function testGet_schema()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Connection::escape_identifier
     * @todo   Implement testEscape_identifier().
     */
    public function testEscape_identifier()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
