<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-21 at 15:44:34.
 */
class DB_Adapter_MySQL_CursorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_Adapter_MySQL_Cursor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_Adapter_MySQL_Cursor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_Adapter_MySQL_Cursor::cast_column
     * @todo   Implement testCast_column().
     */
    public function testCast_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
