<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-21 at 15:46:04.
 */
class DB_Adapter_MySQL_SchemaTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DB_Adapter_MySQL_Schema
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DB_Adapter_MySQL_Schema;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::column_definition
     * @todo   Implement testColumn_definition().
     */
    public function testColumn_definition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::index_definition
     * @todo   Implement testIndex_definition().
     */
    public function testIndex_definition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::add_column
     * @todo   Implement testAdd_column().
     */
    public function testAdd_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::remove_column
     * @todo   Implement testRemove_column().
     */
    public function testRemove_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::update_column
     * @todo   Implement testUpdate_column().
     */
    public function testUpdate_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::remove_index
     * @todo   Implement testRemove_index().
     */
    public function testRemove_index()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::add_index
     * @todo   Implement testAdd_index().
     */
    public function testAdd_index()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::alter_table
     * @todo   Implement testAlter_table().
     */
    public function testAlter_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::create_table
     * @todo   Implement testCreate_table().
     */
    public function testCreate_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::map_column
     * @todo   Implement testMap_column().
     */
    public function testMap_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::map_type
     * @todo   Implement testMap_type().
     */
    public function testMap_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::index_exists_query
     * @todo   Implement testIndex_exists_query().
     */
    public function testIndex_exists_query()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::get_columns_type_map
     * @todo   Implement testGet_columns_type_map().
     */
    public function testGet_columns_type_map()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::get_flip_columns_type_map
     * @todo   Implement testGet_flip_columns_type_map().
     */
    public function testGet_flip_columns_type_map()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::flip_column
     * @todo   Implement testFlip_column().
     */
    public function testFlip_column()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DB_Adapter_MySQL_Schema::inspect
     * @todo   Implement testInspect().
     */
    public function testInspect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
