<?php

	$c = CMS::$current_controller;
	$lang = CMS::lang()->_common;
	$this->use_styles(CMS::stdfile_url('styles/fields/ajaxupload.css'));
	$this->use_scripts(CMS::stdfile_url('scripts/ajaxupload.js'));

	$vname = preg_replace('{[^a-z0-9_]+}','',$name);

	$value = trim($form[$name]);
	$file_path = false;
	if ($value!='') {

		if ($value[0]=='#') {
			$_value = substr($value,1);
			$file_path = CMS::temp_dir().'/'.$_value;
			$file_url = Net_HTTP::Request($c->field_action_url($name,'temp',$item))->parameters(array('filename' => $_value))->uri;
		}

		else {
			$file_path = $type_object->value_to_path($value);
			$file_url = $type_object->value_to_url($value);
		}
	}

	$ffid = "{$form->name}_{$name}";

?>

<?= $this->forms->hidden($name,$tagparms) ?>

<div class="file-field" id="file-field-<?= $name ?>">
	<?php if($item && !$item->is_phantom()) { ?>
	<div class="file-load-indicator" id="file-load-indicator-<?= $name ?>">&nbsp;</div>
	<div data-url="<?= $c->field_action_url($name,'info',$item) ?>" class="file-info" id="file-info-<?= $name ?>"><?php include('info.phtml'); ?></div>
	<div class="upload-file" id="upload-file-<?= $name ?>" data-url="<?= $c->field_action_url($name,'upload',$item,array('code'=>$type_object->temp_code())) ?>"><?= $lang->ta_browse ?></div>
	<?php } else {
		print $lang->unable_in_add;
	} ?>
</div>