<p class="rutube">
  <object width="470" height="353">
    <param name="movie" value="http://video.rutube.ru/<?= $code ?>"></param>
    <param name="wmode" value="window"></param>
    <param name="allowFullScreen" value="true"></param>
    <embed src="http://video.rutube.ru/<?= $code ?>" type="application/x-shockwave-flash" wmode="window" width="470" height="353" allowFullScreen="true" ></embed>
  </object>
</p>