<?php

$id = false;
$width = 640;
$height = 480;

foreach($args_array as $arg) {
	
	$arg = trim($arg);
	
	if ($m = Core_Regexps::match_with_results('{^(\d+)x(\d+)$}',$arg)) {
		$width = $m[1];
		$height = $m[2];
	}
	
	else {
		$id = $arg;
	}
}

if ($id) {
	?><iframe id="player" type="text/html" width="<?= $width ?>" height="<?= $height ?>" src="http://www.youtube.com/embed/<?= $id ?>?enablejsapi=1 frameborder="0" class="youtube"></iframe><?php
}